export const ROLES = {
  PATIENT: 'PATIENT',
  DRIVER: 'DRIVER',
  ADMIN: 'ADMIN',
} as const;

export type UserRole = (typeof ROLES)[keyof typeof ROLES];

export const DRIVER_STATUS = {
  AVAILABLE: 'AVAILABLE',
  BUSY: 'BUSY',
  OFFLINE: 'OFFLINE',
} as const;

export const EMERGENCY_PRIORITY = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
} as const;

export const EMERGENCY_STATUS = {
  PENDING: 'PENDING',
  DISPATCHED: 'DISPATCHED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const TRIP_STATUS = {
  ASSIGNED: 'ASSIGNED',
  EN_ROUTE_PICKUP: 'EN_ROUTE_PICKUP',
  PATIENT_PICKED_UP: 'PATIENT_PICKED_UP',
  EN_ROUTE_HOSPITAL: 'EN_ROUTE_HOSPITAL',
  ARRIVED_HOSPITAL: 'ARRIVED_HOSPITAL',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
} as const;

export const AUDIT_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  STATUS_CHANGE: 'STATUS_CHANGE',
  DISPATCH: 'DISPATCH',
  PAYMENT: 'PAYMENT',
} as const;

export const DEFAULT_PAGINATION = {
  PAGE: 1,
  LIMIT: 10,
  MAX_LIMIT: 100,
};

export const FARE_CONFIG = {
  BASE_FARES: {
    BASIC_LIFE_SUPPORT: 30.0,
    ADVANCED_LIFE_SUPPORT: 50.0,
    PATIENT_TRANSPORT: 20.0,
    NEONATAL: 60.0,
  },
  PER_KM_RATES: {
    BASIC_LIFE_SUPPORT: 3.0,
    ADVANCED_LIFE_SUPPORT: 5.0,
    PATIENT_TRANSPORT: 2.0,
    NEONATAL: 6.0,
  },
  PRIORITY_MULTIPLIER: {
    CRITICAL: 1.25,
    HIGH: 1.15,
    MEDIUM: 1.0,
    LOW: 1.0,
  },
};
